# Generated by Django 3.2.8 on 2021-10-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('update_day', models.DateField(auto_now=True)),
                ('create_day', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
