# Generated by Django 3.2.8 on 2021-10-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('update_day', models.DateTimeField(auto_now=True)),
                ('create_day', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
